#!/bin/bash
esc=$(printf '\033')
CLEANPUSH="\033[0;34m[git-cleanpush]\033[0m"

if $(git diff-index --quiet HEAD --); then
  u="$(git ls-files --exclude-standard --others)"
  if test -z "$u"; then
    exit 0
  fi
fi

untracked=$(git ls-files --exclude-standard --others)
unstaged=$(git diff-files --name-only)
staged=$(git diff --name-only --cached)

cleaned_files="$(echo -e "$untracked\n$unstaged\n$staged" | grep -v ^$ | sort | uniq \
  | sed "s/^/${esc}[0;34m[git-cleanpush]${esc}[0m   /g")"

files="$(git diff-files --name-only)$()"
echo -e "${CLEANPUSH} Uncommitted changes were found:"
echo "${cleaned_files}"

if [[ $(git merge-base master HEAD) == $(git rev-parse HEAD) ]]; then
  echo -e "${CLEANPUSH} Try using: git add --all && git commit"
else
  echo -e "${CLEANPUSH} Try using: git add --all && git commit --amend --no-edit"
fi

exit 1
